---

- name: create additional MariaDB users
  mysql_user:
    name: "{{ item.name }}"
    host: "{{ item.host|d('localhost') }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv }}"
  with_items:
    - "{{ mariadb_users_extra }}"
