---

- name: restart mysql
  service:
    name: mysql
    state: restarted

- name: remove MariaDB test database
  mysql_db:
    name: test
    state: absent
    login_unix_socket: /run/mysqld/mysqld.sock
    login_password: 'placeholder'
